name: solid_signals
description: A high-performance, ultra-lightweight, and fine-grained reactive state management solution for Flutter.
version: 1.0.1
homepage: https://zaszas822moh-dev.github.io/solid_signals_docs/
repository: https://github.com/zaszas822moh-dev/solid_signals

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0